# Generated by Django 2.2.12 on 2022-07-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220705_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='county',
        ),
    ]
